### ISSUE TITLE
Testing wrapped associations w/out persistence

### ISSUE THREAD

**Issue by prognostikos** [nulogy/edr#4]
I want to test some behavior in my model/entity in the most isolated way that I can.

For example, imagine that the `Order` class from `spec/test_data.rb` had an additional method to calculate the total for all of the items for the order:

``` ruby
class Order
  include Edr::Model

  fields :id, :amount, :deliver_at
  wrap_associations :items

  def item_total
    items.map{|i| i.amount}.reduce(0, :+)
  end

  def add_item attrs
    repository.create_item self, attrs
  end
end
```

The only way I can see to test this is to instantiate a new `ItemData`  object and use it in a test as follows:

``` ruby
  describe "Testing wrapped associations w/out persistence" do
    example do
      item  = ItemData.new(amount: 4)
      order = Order.build OpenStruct.new(items: [item])
      order.item_total.should eq 4
    end

    example do
      order = Order.build OpenStruct.new(items: [])
      order.item_total.should eq 0
    end
  end
```

This works, but it seems like it needs AR, checks if the ItemData table exists, etc.

I would like to do something like:

``` ruby
describe "Testing wrapped associations w/out persistence" do
   example do
      item = double('item')
      item.should_receive(:amount).and_return(2)
      order = Order.new
      order.items = [item]
      order.item_total.should eq 4
    end
end
```

(this gives me a `NoMethodError` for `items=`)

or

``` ruby
describe "Testing wrapped associations w/out persistence" do
     example do
      item = double('item')
      item.should_receive(:amount).and_return(2)
      order = Order.build OpenStruct.new(items: [item])
      order.item_total.should eq 4
    end
end
```

(this tells me that there's no model class for `RSpec::Mocks::Mock`)

Am I just running into limitations of what Edr is supposed to do, or should this work?

Or to put it another way, how do you test Entity methods that use associated data in the most isolated way possible?

**Comment by prognostikos** [comment]
I should add that I can stub out the `items` method, but that seems very brittle to me:

``` ruby
describe "Testing wrapped associations w/out persistence" do
  example do
    item = double('item')
    item.should_receive(:amount).and_return(2)
    order = Order.new
    order.should_receive(:items).and_return([item, item])
    order.item_total.should eq 4
  end
end
```

**Comment by vsavkin** [comment]
Order.build OpenStruct.new(items:[item])

Everything you are passing to the build function is just data and will be wrapped. That’s why when you are calling:

Order.build OpenStruct.new(items:[item])

you are getting: ‘No model class for RSpec::Mocks::Mock’. It’s trying to wrap that data object (which is just a stub).

Fundamentally, the problem exists due to the fact that all models require data objects. 

Things you can do:
1. Using the repository field for accessing associations.

```
class Order
  def items
     repository.items_for(self)
  end 
end
```
1. Stubbing      
   
   order = Order.build
   order.stub(items: [item])
2. Managing associations yourself
   
   class Order
      attr_accessor items
   end

In this case, the repository will have to handle it.

I was also thinking about having some sort of helper for creating test data objects. It will generate a test data class for every passed model. So you’ll be able to do the following:

```
EDR.configure_for_test(Order, Item)
Order.build order_data(items: [item_data(amount: 10)])
```

**Comment by prognostikos** [comment]
Thanks for your input, Victor.
